sudo: required
services:
  - docker

script: 
  - docker run alexeball/cafamReact-test npm run test -- --coverage

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_AUTH_TOKEN
  on: 
    branch: master