language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - npm test
env:
  - CI=true
deploy:
  provider: heroku
  app: https://stormy-shelf-62092.herokuapp.com
  api_key:
    secure: $HEROKU_AUTH_TOKEN
  strategy: git
  on: 
    branch: master